[package]
name = "TCC-TSP"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.37", features = ["derive"] }
csv = "1.3.1"
ordered-float = "5.0.0"
plotters = "0.3.7"
rand = "0.9.1"
